# This workflow will build a Java project with Gradle
# For more information check https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build

      - name: Create artifact directory structure
        run: |
          mkdir -p artifacts
          echo "Simply click the version you need, drag the jar that does ! NOT ! end in 'all' or 'sources', and drag into your mods folder. ;)" >> artifacts/README.txt
          for version in 1.20.1 1.20.2 1.20.4 1.20.6; do
            mkdir -p artifacts/$version/devlibs
            mkdir -p artifacts/$version/libs
            cp ./versions/$version/build/devlibs/*.jar artifacts/$version/devlibs/
            cp ./versions/$version/build/libs/*.jar artifacts/$version/libs/
          done

      - name: Compute hashes
        run: |
          touch artifacts/hashes.txt
          for jar in $(find artifacts -name '*.jar'); do
            sha256sum $jar >> artifacts/hashes.txt
          done

      - name: Archive Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: artifacts
